### ISSUE TITLE
Codebase not updated

### ISSUE THREAD

**Issue by aerofur** [BallisticStusios/front-detail-E2-pack#1]
Your main repo code base isnt being updated. 

I would suggest that you instead of zipping your e2s and putting them in during release that you upload them directly to the github. Benefits of this are; 

- Your code is backed up
- Editing code outside of the game editor, (synatx highlighting can be added with a gitatt file)
- Releasing is now only a single click

Just an idea, also because people dont always understand that you have to goto the releases tab, instead of a direct repo clone.

**Comment by Ballistic-Studios** [comment]
I got u fam
